name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      ORG: guardian-security
      SKIP_PYTHON: false
      PYTHON_VERSION: 3.9
      PIP_REQUIREMENTS_FILES: requirements.txt
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
